/*
   Tileset generated by Jo Map Editor v6.1
*/

#ifndef __XBUTTONMAP_H__
# define __XBUTTONMAP_H__

/* 2 tiles */
static const jo_tile    XButtonMap[] =
{
	{0, 0, 24, 24},
	{24, 0, 24, 24}
};

#endif /* !__XBUTTONMAP_H__ */
